# Auto-generated by ./configure. Delegates to GNU make.
GNUMAKE = make

all spacetrader clean install uninstall:
	$(GNUMAKE) -f GNUmakefile $@ 		CC="$(CC)" CFLAGS="$(CFLAGS)" CPPFLAGS="$(CPPFLAGS)" LDFLAGS="$(LDFLAGS)" 		NCURSES_CFLAGS="$(NCURSES_CFLAGS)" NCURSES_LIBS="$(NCURSES_LIBS)" 		DESTDIR="$(DESTDIR)" BINDIR="$(BINDIR)" MAN6DIR="$(MAN6DIR)" 		INSTALL="$(INSTALL)" RM="$(RM)"

.PHONY: all spacetrader clean install uninstall
